import {
  Activity,
  BarChart3,
  Bell,
  CalendarCheck,
  ClipboardList,
  CreditCard,
  LayoutDashboard,
  MapPin,
  MessageSquare,
  Package,
  Settings,
  UserCircle,
  Users,
  Wrench,
} from "lucide-react";
import type { AppNavItem } from "../domain/models/admin";
import { UserRole } from "../store/session-store";

export const ROLE_NAVIGATION: Record<UserRole, AppNavItem[]> = {
  [UserRole.SUPER_ADMIN]: [
    { id: "dashboard", label: "Dashboard", path: "/dashboard", module: "dashboard", icon: <LayoutDashboard size={20} /> },
    { id: "requests", label: "Requests", path: "/service-requests", module: "service-requests", icon: <Wrench size={20} /> },
    { id: "bookings", label: "Bookings", path: "/bookings", module: "service-requests", icon: <CalendarCheck size={20} /> },
    { id: "customers", label: "Customers", path: "/customers", module: "customers", icon: <UserCircle size={20} /> },
    { id: "team", label: "Team", path: "/team", module: "team", icon: <Users size={20} /> },
    { id: "operations", label: "Operations", path: "/operations/dashboard", module: "operations", icon: <Activity size={20} /> },
    { id: "inventory", label: "Inventory", path: "/inventory", module: "inventory", icon: <Package size={20} /> },
    { id: "billing", label: "Billing", path: "/billing/dashboard", module: "billing", icon: <CreditCard size={20} /> },
    { id: "support", label: "Support", path: "/support/dashboard", module: "support", icon: <MessageSquare size={20} /> },
    { id: "notifications", label: "Notifications", path: "/notifications", module: "settings", icon: <Bell size={20} /> },
    { id: "settings", label: "Settings", path: "/settings", module: "settings", icon: <Settings size={20} /> },
  ],
  [UserRole.ADMIN]: [
    { id: "dashboard", label: "Dashboard", path: "/dashboard", module: "dashboard", icon: <LayoutDashboard size={20} /> },
    { id: "requests", label: "Requests", path: "/service-requests", module: "service-requests", icon: <Wrench size={20} /> },
    { id: "bookings", label: "Bookings", path: "/bookings", module: "service-requests", icon: <CalendarCheck size={20} /> },
    { id: "customers", label: "Customers", path: "/customers", module: "customers", icon: <UserCircle size={20} /> },
    { id: "team", label: "Team", path: "/team", module: "team", icon: <Users size={20} /> },
    { id: "operations", label: "Operations", path: "/operations/dashboard", module: "operations", icon: <Activity size={20} /> },
    { id: "notifications", label: "Notifications", path: "/notifications", module: "settings", icon: <Bell size={20} /> },
    { id: "settings", label: "Settings", path: "/settings", module: "settings", icon: <Settings size={20} /> },
  ],
  [UserRole.OPS_MANAGER]: [
    { id: "dashboard", label: "Dashboard", path: "/dashboard", module: "dashboard", icon: <LayoutDashboard size={20} /> },
    { id: "requests", label: "Requests", path: "/service-requests", module: "service-requests", icon: <Wrench size={20} /> },
    { id: "bookings", label: "Bookings", path: "/bookings", module: "service-requests", icon: <CalendarCheck size={20} /> },
    { id: "team", label: "Team", path: "/team", module: "team", icon: <Users size={20} /> },
    { id: "operations", label: "Operations", path: "/operations/dashboard", module: "operations", icon: <Activity size={20} /> },
    { id: "map", label: "Map", path: "/operations/map", module: "operations", icon: <MapPin size={20} /> },
    { id: "notifications", label: "Notifications", path: "/notifications", module: "settings", icon: <Bell size={20} /> },
    { id: "profile", label: "Profile", path: "/profile", module: "dashboard", icon: <UserCircle size={20} /> },
  ],
  [UserRole.OPS_EXECUTIVE]: [
    { id: "dashboard", label: "Dashboard", path: "/dashboard", module: "dashboard", icon: <LayoutDashboard size={20} /> },
    { id: "requests", label: "Requests", path: "/service-requests", module: "service-requests", icon: <Wrench size={20} /> },
    { id: "bookings", label: "Bookings", path: "/bookings", module: "service-requests", icon: <CalendarCheck size={20} /> },
    { id: "team", label: "Team", path: "/team", module: "team", icon: <Users size={20} /> },
    { id: "dispatch", label: "Dispatch", path: "/operations/dispatch", module: "operations", icon: <ClipboardList size={20} /> },
    { id: "notifications", label: "Notifications", path: "/notifications", module: "settings", icon: <Bell size={20} /> },
    { id: "profile", label: "Profile", path: "/profile", module: "dashboard", icon: <UserCircle size={20} /> },
  ],
  [UserRole.SUPPORT]: [
    { id: "dashboard", label: "Dashboard", path: "/dashboard", module: "dashboard", icon: <LayoutDashboard size={20} /> },
    { id: "requests", label: "Requests", path: "/service-requests", module: "service-requests", icon: <Wrench size={20} /> },
    { id: "bookings", label: "Bookings", path: "/bookings", module: "service-requests", icon: <CalendarCheck size={20} /> },
    { id: "customers", label: "Customers", path: "/customers", module: "customers", icon: <UserCircle size={20} /> },
    { id: "support", label: "Support", path: "/support/dashboard", module: "support", icon: <MessageSquare size={20} /> },
    { id: "notifications", label: "Notifications", path: "/notifications", module: "settings", icon: <Bell size={20} /> },
    { id: "profile", label: "Profile", path: "/profile", module: "dashboard", icon: <UserCircle size={20} /> },
  ],
  [UserRole.TECHNICIAN]: [
    { id: "dashboard", label: "Home", path: "/technician/home", module: "jobs", icon: <LayoutDashboard size={20} /> },
    { id: "jobs", label: "Jobs", path: "/field/jobs", module: "jobs", icon: <ClipboardList size={20} /> },
    { id: "profile", label: "Profile", path: "/profile", module: "dashboard", icon: <UserCircle size={20} /> },
  ],
  [UserRole.HELPER]: [
    { id: "dashboard", label: "Home", path: "/technician/home", module: "jobs", icon: <LayoutDashboard size={20} /> },
    { id: "jobs", label: "Jobs", path: "/field/jobs", module: "jobs", icon: <ClipboardList size={20} /> },
    { id: "profile", label: "Profile", path: "/profile", module: "dashboard", icon: <UserCircle size={20} /> },
  ],
  [UserRole.INVENTORY_MANAGER]: [
    { id: "dashboard", label: "Dashboard", path: "/inventory", module: "inventory", icon: <Package size={20} /> },
    { id: "requests", label: "Requests", path: "/inventory/requests", module: "inventory", icon: <ClipboardList size={20} /> },
    { id: "notifications", label: "Notifications", path: "/notifications", module: "settings", icon: <Bell size={20} /> },
    { id: "profile", label: "Profile", path: "/profile", module: "dashboard", icon: <UserCircle size={20} /> },
  ],
  [UserRole.BILLING_EXECUTIVE]: [
    { id: "billing", label: "Billing", path: "/billing/dashboard", module: "billing", icon: <CreditCard size={20} /> },
    { id: "finance", label: "Finance", path: "/finance/dashboard", module: "finance", icon: <BarChart3 size={20} /> },
    { id: "notifications", label: "Notifications", path: "/notifications", module: "settings", icon: <Bell size={20} /> },
    { id: "profile", label: "Profile", path: "/profile", module: "dashboard", icon: <UserCircle size={20} /> },
  ],
  [UserRole.FINANCE_MANAGER]: [
    { id: "billing", label: "Billing", path: "/billing/dashboard", module: "billing", icon: <CreditCard size={20} /> },
    { id: "finance", label: "Finance", path: "/finance/dashboard", module: "finance", icon: <BarChart3 size={20} /> },
    { id: "notifications", label: "Notifications", path: "/notifications", module: "settings", icon: <Bell size={20} /> },
    { id: "profile", label: "Profile", path: "/profile", module: "dashboard", icon: <UserCircle size={20} /> },
  ],
  [UserRole.MARKETING_MANAGER]: [
    { id: "dashboard", label: "Dashboard", path: "/marketing/dashboard", module: "settings", icon: <LayoutDashboard size={20} /> },
    { id: "notifications", label: "Notifications", path: "/notifications", module: "settings", icon: <Bell size={20} /> },
    { id: "settings", label: "Settings", path: "/settings", module: "settings", icon: <Settings size={20} /> },
    { id: "profile", label: "Profile", path: "/profile", module: "dashboard", icon: <UserCircle size={20} /> },
  ],
};

